name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Continous integration tests
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
      - name: Verify code with ESLint
        run: npm run eslint
